# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://seecsos.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "#"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "NUST HACKATHON | January 2017"
  description: "Two Day Open Source Event Full of Hack Activities."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "NUST HACKATHON"
  description: "Two Day Open Source Event Full of Hack Activities!"
  date:        "15 & 16 January 2017"
  location:    "Islamabad, Pakistan"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "#"
      - text: "Sponsor"
        href: "mailto:usmanwardag@gmail.com"

  about:
    description: >
      List of hacks developed during the first hack day, so students know what to expect.
  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "OPEN-SOURCE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "GREAT MENTORS."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "HACKING."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at any school of NUST or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        Venue will be shared soon.
    - question: "Are there any prizes for winners?"
      answer: >
        Yes, we are in contact with some sponsors to make sure winners are rewarded!
    - question: "Would there be food?"
      answer: >
        Yes!
    - question: "What do you mean by open source?"
      answer: >
        All the hacks that you build over the duration of hackathon would be shared publicly. This allows you 
        to develop your open source presence to impress your future employers.
    - question: "Is there a code of conduct?"
      answer: >
        Yes, we follow the one designed by MLH for reference, and we enforce it very strongly. You can
        [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
